### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by chkpwd** [crutonjohn/external-dns-opnsense-webhook#16]
I'm on mobile right now but I can fix formatting later.

```
fullnameOverride: external-dns-opnsense
logLevel: debug
provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
      tag: v0.1.0
    env:
      - name: OPNSENSE_API_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-opnsense-secret
            key: api_secret
      - name: OPNSENSE_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-opnsense-secret
            key: api_key
      - name: OPNSENSE_HOST
        value: http://172.16.16.1
      - name: OPNSENSE_SKIP_TLS_VERIFY
        value: "true"
      - name: LOG_LEVEL
        value: debug
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
extraArgs:
  - --ignore-ingress-tls-spec
policy: sync
sources: ["ingress", "service"]
registry: noop
domainFilters: ["local.chkpwd.com"]
```

Logs:

```

eadTimeout:5s WebhookProviderWriteTimeout:10s WebhookServer:false}"
time="2024-06-19T17:08:09Z" level=info msg="Instantiating new Kubernetes client"
time="2024-06-19T17:08:09Z" level=debug msg="apiServerURL: "
time="2024-06-19T17:08:09Z" level=debug msg="kubeConfig: "
time="2024-06-19T17:08:09Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2024-06-19T17:08:09Z" level=info msg="Created Kubernetes client https://172.24.0.1:443"
time="2024-06-19T17:08:10Z" level=debug msg="Failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
time="2024-06-19T17:08:10Z" level=debug msg="Failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
time="2024-06-19T17:08:11Z" level=debug msg="Failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
time="2024-06-19T17:08:12Z" level=debug msg="Failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
time="2024-06-19T17:08:14Z" level=debug msg="Failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
time="2024-06-19T17:08:17Z" level=debug msg="Failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
time="2024-06-19T17:08:17Z" level=fatal msg="failed to connect to plugin api: Get \"http://localhost:8888\": dial tcp [::1]:8888: connect: connection refused"
```
